obj-m += mymodule.o
 
all:
		make -C /lib/modules/5.2.8org200301/build M=/home/kau/jwbang/linux-5.2.8_org/mymodule modules
 
clean:
		make -C /lib/modules/5.2.8org200301/build M=/home/kau/jwbang/linux-5.2.8_org/mymodule clean
